#!/usr/bin/env bash
set -euo pipefail

TARGET_ENV="${1:-dev}"
TAG_FILE="tags/${TARGET_ENV}.versions"

cp "$TAG_FILE" .env.runtime # Bring docker TAGs

cat <<EOF >> .env.runtime

PORT_FRONTEND=${PORT_FRONTEND}
PORT_BACKEND=${PORT_BACKEND}
PORT_LLM=${PORT_LLM}

MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_DATABASE=${MYSQL_DATABASE}
MYSQL_USER=${MYSQL_USER}
MYSQL_PASSWORD=${MYSQL_PASSWORD}

CLICKHOUSE_DATABASE=${CLICKHOUSE_DB}
CLICKHOUSE_USERNAME=${CLICKHOUSE_USER}
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}

JWT_SECRET_KEY=${JWT_SECRET}

SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

SERVER_URL=${SERVER_URL}
FRONTEND_URL=${FRONTEND_URL}
LLM_SERVER_URL=${LLM_SERVER_URL}

LLM_PROVIDER=${LLM_PROVIDER}
LLM_MODEL=${LLM_MODEL}
LLM_BASE_URL=${LLM_BASE_URL}

OPENAI_API_KEY=${OPENAI_API_KEY}
GROQ_API_KEY=${GROQ_API_KEY}

BACKEND_BASE_URL=${SERVER_URL}

CLICKHOUSE_HOST=clickhouse
CLICKHOUSE_PORT=8123

EOF

echo ".env.runtime created for ${TARGET_ENV}"