#!/usr/bin/env bash
set -euo pipefail

TARGET_ENV="${1:-dev}"
TAG_FILE="tags/${TARGET_ENV}.versions"

cp "$TAG_FILE" .env.runtime

cat <<EOF >> .env.runtime

PORT_FRONTEND=${PORT_FRONTEND}
PORT_BACKEND=${PORT_BACKEND}
# PORT_AI=${PORT_AI}

MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_DATABASE=${MYSQL_DATABASE}
MYSQL_USER=${MYSQL_USER}
MYSQL_PASSWORD=${MYSQL_PASSWORD}

CLICKHOUSE_DATABASE=${CLICKHOUSE_DB}
CLICKHOUSE_USERNAME=${CLICKHOUSE_USER}
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}

JWT_SECRET_KEY=${JWT_SECRET}

SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

CLICKHOUSE_HOST=clickhouse
CLICKHOUSE_PORT=8123

EOF

echo ".env.runtime created for ${TARGET_ENV}"